// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8UFkhCJn0pLuvhGCOSnYdqvRI6t54rk',
    appId: '1:583542775440:web:fb1fb6be65ee36030a8215',
    messagingSenderId: '583542775440',
    projectId: 'ictemos',
    authDomain: 'ictemos.firebaseapp.com',
    storageBucket: 'ictemos.appspot.com',
    measurementId: 'G-BC9PH7VG05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgn9IDs9KZR5aMRmHNWpimhZjtXIhkzw',
    appId: '1:583542775440:android:db7dbf2dfb274a790a8215',
    messagingSenderId: '583542775440',
    projectId: 'ictemos',
    storageBucket: 'ictemos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlaVLScObrA4fFOsIfNjDfk0c9KmuXLKc',
    appId: '1:583542775440:ios:1310af5d6a026c000a8215',
    messagingSenderId: '583542775440',
    projectId: 'ictemos',
    storageBucket: 'ictemos.appspot.com',
    iosClientId: '583542775440-ehdhgqj7jprq1tslmq9vbddt04ubl9ii.apps.googleusercontent.com',
    iosBundleId: 'com.firstemos.todoapp',
  );
}
