// class DatabaseAlreadyOpenException implements Exception {}
// class UnableToGetDocumentsDirectory implements Exception {}
// class DatabaseNotOpenedException implements Exception {}
// class CouldNotDeleteTheUser implements Exception {}
// class UserAlreadyExistException implements Exception {}
// class CouldNotFindUserException implements Exception {}
// class CouldNotDeleteNoteException implements Exception {}
// class CouldNotFindNoteException implements Exception {}
// class CouldNotUpdateNoteException implements Exception {}
// class UserShouldBeSetBeforeReadingAllNotesException implements Exception {}
